/**
 * EconomicRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EconomicRepository Port
 *
 * DDD: Application port for economicrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateEconomicsSnapshotInput, CreateEconomicsSnapshotOutput, GetEconomicsSnapshotInput, GetEconomicsSnapshotOutput, ListEconomicsSnapshotsInput, ListEconomicsSnapshotsOutput } from "../dto/economic.dto";
export interface EconomicRepository {
  listEconomicsSnapshots(input: ListEconomicsSnapshotsInput): Promise<ListEconomicsSnapshotsOutput>;
  createEconomicsSnapshot(input: CreateEconomicsSnapshotInput): Promise<CreateEconomicsSnapshotOutput>;
  getEconomicsSnapshot(input: GetEconomicsSnapshotInput): Promise<GetEconomicsSnapshotOutput>;
}

export type { CreateEconomicsSnapshotInput, CreateEconomicsSnapshotOutput, GetEconomicsSnapshotInput, GetEconomicsSnapshotOutput, ListEconomicsSnapshotsInput, ListEconomicsSnapshotsOutput } from "../dto/economic.dto";
