/**
 * ExecuteRevokeDataPurpose - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRevokeDataPurpose Use Case
 *
 * DDD: Application use case for get DataPurpose.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RevokeDataPurposeInput, RevokeDataPurposeOutput } from "../dto/data-purpose.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { DataPurposeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRevokeDataPurpose {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataPurpose: DataPurposeRepository
  ) {}

  async execute(input: RevokeDataPurposeInput): Promise<RevokeDataPurposeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dataPurposeId) {
      throw new ValidationError("dataPurposeId is required");
    }
    const datapurposeId = (input as any).dataPurposeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataPurpose.revokeDataPurpose({ dataPurposeId: datapurposeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${datapurposeId}`);
    }

    return entity as RevokeDataPurposeOutput;
  }
}
