/**
 * ExecuteCheckDataExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCheckDataExport Use Case
 *
 * DDD: Application use case for get ExportCheck.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CheckDataExportInput, CheckDataExportOutput } from "../dto/export-check.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { ExportCheckRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteCheckDataExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportCheck: ExportCheckRepository
  ) {}

  async execute(input: CheckDataExportInput): Promise<CheckDataExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec: attributeCount, dealId, purpose
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dealId) {
      throw new ValidationError("dealId is required");
    }
    const dealId = (input as any).dealId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exportCheck.checkDataExport({ dealId: dealId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${dealId}`);
    }

    return entity as CheckDataExportOutput;
  }
}
