/**
 * ExecuteListDataPurposes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataPurposes Use Case
 *
 * DDD: Application use case for list DataPurpose.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataPurposesInput, ListDataPurposesOutput } from "../dto/data-purpose.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { DataPurposeRepository } from "../ports";

export class ExecuteListDataPurposes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataPurpose: DataPurposeRepository
  ) {}

  async execute(input: ListDataPurposesInput): Promise<ListDataPurposesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dataPurpose.listDataPurposes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataPurposesOutput;
  }
}
