/**
 * ExecuteCreateChannelNode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateChannelNode Use Case
 *
 * DDD: Application use case for create Channel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateChannelNodeInput, CreateChannelNodeOutput } from "../dto/channel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { ChannelRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateChannelNode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly channel: ChannelRepository
  ) {}

  async execute(input: CreateChannelNodeInput): Promise<CreateChannelNodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.chnId();

    // All field names extracted from OpenAPI spec: dealId, geography, nodeType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.dealId) {
      throw new ValidationError("dealId is required");
    }
    if (!input.geography) {
      throw new ValidationError("geography is required");
    }
    if (!input.nodeType) {
      throw new ValidationError("nodeType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (channels domain)
    const entityId = this.idGenerator.chnId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.channel.createChannelNode({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateChannelNodeOutput;
  }
}
