/**
 * Datapurpose DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Datapurpose Domain Module - Composition root
 *
 * DDD: Composition root for datapurpose domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DataPurposeRepositoryAdapter,
} from "@partnora/adapters/datapurpose";
import { getIdGeneratorService } from "@partnora/adapters";
import type { AdapterDynamoDBClient } from "@partnora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCheckDataExport,
  ExecuteCreateDataPurpose,
  ExecuteGetDataPurpose,
  ExecuteListDataPurposes,
  ExecuteRevokeDataPurpose,
} from "@partnora/services/datapurpose/usecases";
// Ports (interfaces)
import type {
  DataPurposeRepository,
} from "@partnora/services/datapurpose/ports";

export interface DatapurposeDomainModule {
  repos: {
    dataPurposes: DataPurposeRepository;
  };
  useCases: {
    dataPurposes: {
      create: ExecuteCreateDataPurpose;
      get: ExecuteRevokeDataPurpose;
      list: ExecuteListDataPurposes;
    };
  };
}

export function buildDatapurposeDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DatapurposeDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dataPurposes?: DataPurposeRepository;
    } = {};

    obj.dataPurposes = new DataPurposeRepositoryAdapter(dynamoClient);
    return {
      dataPurposes: obj.dataPurposes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dataPurposes: {
      create: new ExecuteCreateDataPurpose(executionContext, idGenerator, repos.dataPurposes),
      get: new ExecuteRevokeDataPurpose(executionContext, idGenerator, repos.dataPurposes),
      list: new ExecuteListDataPurposes(executionContext, idGenerator, repos.dataPurposes),
    },
  };
  return { repos, useCases: useCases as DatapurposeDomainModule["useCases"] };
}
