/**
 * Deals DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deals Domain Module - Composition root
 *
 * DDD: Composition root for deals domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DealRepositoryAdapter,
  ExitRepositoryAdapter,
  LaunchRepositoryAdapter,
  MaReassessmentRepositoryAdapter,
  RemediateRepositoryAdapter,
  SubmitGateRepositoryAdapter,
} from "@partnora/adapters/deals";
import { getIdGeneratorService } from "@partnora/adapters";
import type { AdapterDynamoDBClient } from "@partnora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDeal,
  ExecuteGetDeal,
  ExecuteLaunchDeal,
  ExecuteListDeals,
  ExecuteRemediateDeal,
  ExecuteStartDealExit,
  ExecuteStartMaReassessment,
  ExecuteSubmitDealToGates,
  ExecuteUpdateDeal,
} from "@partnora/services/deals/usecases";
// Ports (interfaces)
import type {
  DealRepository,
  ExitRepository,
  LaunchRepository,
  MaReassessmentRepository,
  RemediateRepository,
  SubmitGateRepository,
} from "@partnora/services/deals/ports";

export interface DealsDomainModule {
  repos: {
    deals: DealRepository;
    exits: ExitRepository;
    launches: LaunchRepository;
    maReassessments: MaReassessmentRepository;
    remediates: RemediateRepository;
    submitGates: SubmitGateRepository;
  };
  useCases: {
    deals: {
      create: ExecuteCreateDeal;
      get: ExecuteGetDeal;
      list: ExecuteListDeals;
      update: ExecuteUpdateDeal;
    };
    exits: {
      create: ExecuteStartDealExit;
    };
    launches: {
      get: ExecuteLaunchDeal;
    };
    maReassessments: {
      create: ExecuteStartMaReassessment;
    };
    remediates: {
      get: ExecuteRemediateDeal;
    };
    submitGates: {
      create: ExecuteSubmitDealToGates;
    };
  };
}

export function buildDealsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DealsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      deals?: DealRepository;
      exits?: ExitRepository;
      launches?: LaunchRepository;
      maReassessments?: MaReassessmentRepository;
      remediates?: RemediateRepository;
      submitGates?: SubmitGateRepository;
    } = {};

    obj.deals = new DealRepositoryAdapter(dynamoClient);
    obj.exits = new ExitRepositoryAdapter(dynamoClient);
    obj.launches = new LaunchRepositoryAdapter(dynamoClient);
    obj.maReassessments = new MaReassessmentRepositoryAdapter(dynamoClient);
    obj.remediates = new RemediateRepositoryAdapter(dynamoClient);
    obj.submitGates = new SubmitGateRepositoryAdapter(dynamoClient);
    return {
      deals: obj.deals!,
      exits: obj.exits!,
      launches: obj.launches!,
      maReassessments: obj.maReassessments!,
      remediates: obj.remediates!,
      submitGates: obj.submitGates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    deals: {
      create: new ExecuteCreateDeal(executionContext, idGenerator, repos.deals),
      get: new ExecuteGetDeal(executionContext, idGenerator, repos.deals),
      list: new ExecuteListDeals(executionContext, idGenerator, repos.deals),
      update: new ExecuteUpdateDeal(executionContext, idGenerator, repos.deals),
    },
    exits: {
      create: new ExecuteStartDealExit(executionContext, idGenerator, repos.exits),
    },
    launches: {
      get: new ExecuteLaunchDeal(executionContext, idGenerator, repos.launches),
    },
    maReassessments: {
      create: new ExecuteStartMaReassessment(executionContext, idGenerator, repos.maReassessments),
    },
    remediates: {
      get: new ExecuteRemediateDeal(executionContext, idGenerator, repos.remediates),
    },
    submitGates: {
      create: new ExecuteSubmitDealToGates(executionContext, idGenerator, repos.submitGates),
    },
  };
  return { repos, useCases: useCases as DealsDomainModule["useCases"] };
}
