/**
 * AttachParent DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttachParent DTOs
 *
 * DDD: Application DTOs for AttachParent use cases.
 */

import type { AttachPilotParentParams, AttachPilotParentRequestInput } from "@partnora/core/pilots/types";

export type AttachPilotParentInput = AttachPilotParentParams & AttachPilotParentRequestInput;

export type AttachPilotParentOutput = {};
