/**
 * Pilot DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pilot DTOs
 *
 * DDD: Application DTOs for Pilot use cases.
 */

import type { CreatePilotRequestInput, GetPilotParams, ListPilotsParams } from "@partnora/core/pilots/types";

export type ListPilotsInput = ListPilotsParams;

export type CreatePilotInput = CreatePilotRequestInput;

export type GetPilotInput = GetPilotParams;

export type ListPilotsOutput = {};

export type CreatePilotOutput = {};

export type GetPilotOutput = {};
