/**
 * GetEconomicsSnapshot handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getEconomicsSnapshot } from "@partnora/api-server/domains/economics/handlers";
import type { EconomicsDDDDependencies } from "@partnora/api-server/domains/economics";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { ECONOMICS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetEconomicsSnapshot", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EconomicsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EconomicsDDDDependencies>(
      ECONOMICS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetEconomicsSnapshot, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { economicsSnapshotId: entity.id };

    await getEconomicsSnapshot(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetEconomicsSnapshot.execute).toHaveBeenCalledWith(expect.objectContaining({ economicsSnapshotId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { economicsSnapshotId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetEconomicsSnapshot, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getEconomicsSnapshot(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
