/**
 * ExecuteGetPartner - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPartner Use Case
 *
 * DDD: Application use case for get Partner.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPartnerInput, GetPartnerOutput } from "../dto/partner.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { PartnerRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPartner {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly partner: PartnerRepository
  ) {}

  async execute(input: GetPartnerInput): Promise<GetPartnerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).partnerId) {
      throw new ValidationError("partnerId is required");
    }
    const partnerId = (input as any).partnerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.partner.getPartner({ partnerId: partnerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${partnerId}`);
    }

    return entity as GetPartnerOutput;
  }
}
