/**
 * ExecuteListOwnershipRules - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOwnershipRules Use Case
 *
 * DDD: Application use case for list OwnershipRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOwnershipRulesInput, ListOwnershipRulesOutput } from "../dto/ownership-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { OwnershipRuleRepository } from "../ports";

export class ExecuteListOwnershipRules {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ownershipRule: OwnershipRuleRepository
  ) {}

  async execute(input: ListOwnershipRulesInput): Promise<ListOwnershipRulesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ownId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ownershipRule.listOwnershipRules({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOwnershipRulesOutput;
  }
}
