/**
 * ExecuteCreateOwnershipRule - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateOwnershipRule Use Case
 *
 * DDD: Application use case for create OwnershipRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateOwnershipRuleInput, CreateOwnershipRuleOutput } from "../dto/ownership-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { OwnershipRuleRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateOwnershipRule {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ownershipRule: OwnershipRuleRepository
  ) {}

  async execute(input: CreateOwnershipRuleInput): Promise<CreateOwnershipRuleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ownId();

    // All field names extracted from OpenAPI spec: complaintLiability, dealId, journeyStep, ownerParty, routingSlaHours
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.ownerParty) {
      throw new ValidationError("ownerParty is required");
    }
    if (!input.journeyStep) {
      throw new ValidationError("journeyStep is required");
    }
    if (!input.dealId) {
      throw new ValidationError("dealId is required");
    }
    if (!input.complaintLiability) {
      throw new ValidationError("complaintLiability is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (ownership domain)
    const entityId = this.idGenerator.ownId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.ownershipRule.createOwnershipRule({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateOwnershipRuleOutput;
  }
}
