/**
 * GetPartner DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPartnerParams } from "@partnora/core/partners";

export function createGetPartnerRequest(overrides: Partial<GetPartnerParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
