/**
 * Score DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Score DTOs
 *
 * DDD: Application DTOs for Score use cases.
 */

import type { ScoreOpportunityParams, ScoreOpportunityRequestInput } from "@partnora/core/opportunities/types";

export type ScoreOpportunityInput = ScoreOpportunityParams & ScoreOpportunityRequestInput;

export type ScoreOpportunityOutput = {};
