/**
 * ExitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExitRepository,
} from "@partnora/services/deals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExitRepositoryDdb } from "./exit-repository.ddb.js";

/**
 * ExitRepositoryAdapter
 *
 * Implements ExitRepository port for infrastructure layer.
 */
export class ExitRepositoryAdapter implements ExitRepository {
  private readonly ddb: ExitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExitRepositoryDdb(this.dynamoClient);
  }

  async startDealExit(input: Parameters<ExitRepository['startDealExit']>[0]): Promise<Awaited<ReturnType<ExitRepository['startDealExit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.startDealExit(input);
  }
}
