/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./deal-repository.ddb.js";
export * from "./exit-repository.ddb.js";
export * from "./launch-repository.ddb.js";
export * from "./ma-reassessment-repository.ddb.js";
export * from "./remediate-repository.ddb.js";
export * from "./submit-gate-repository.ddb.js";
export * from "./deal-repository.adapter.js";
export * from "./exit-repository.adapter.js";
export * from "./launch-repository.adapter.js";
export * from "./ma-reassessment-repository.adapter.js";
export * from "./remediate-repository.adapter.js";
export * from "./submit-gate-repository.adapter.js";
