/**
 * Incident Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/audits.openapi.types.js";
import { schemas } from "../schemas/audits.schemas.js";

/**
 * Entity: IncidentEntity
 * Description: Represents the Incident domain model.
 * Source: schemas.Incident
 * Type: Domain Entity (API)
 */
export const IncidentEntitySchema = schemas.Incident;
export type IncidentEntity = components["schemas"]["Incident"];
