/**
 * CreateExit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { StartDealExitParams } from "@partnora/core/deals";

export function createCreateExitRequest(overrides: Partial<StartDealExitParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
