/**
 * Repository interface for Incident
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  IncidentEntity
} from "../models/incident.entity.js";
import type {
  ListIncidentsParams,
  Incident
} from "../types/index.js";
/**
 * IncidentRepository Interface
 */
export interface IncidentRepository extends CreateReadRepository<IncidentEntity, Incident, string, ListIncidentsParams> {

}
