/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Conflicts Domain Use Cases
 * 
 * List of all use case names for the conflicts domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONFLICTS_USE_CASES = [
  "executeAcceptConflictMitigation",
  "executeCreateConflict",
  "executeGetConflict",
  "executeListConflicts"
] as const;
