/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Economics Domain Use Cases
 * 
 * List of all use case names for the economics domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ECONOMICS_USE_CASES = [
  "executeCreateEconomicsSnapshot",
  "executeGetEconomicsSnapshot",
  "executeListEconomicsSnapshots"
] as const;
