/**
 * GetDeal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDeal } from "@partnora/api-server/domains/deals/handlers";
import type { DealsDDDDependencies } from "@partnora/api-server/domains/deals";
import { createDeal as createDealEntity } from "@partnora/factories/deals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { DEALS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDeal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DealsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DealsDDDDependencies>(
      DEALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDealEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDeal, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { dealId: entity.id };

    await getDeal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDeal.execute).toHaveBeenCalledWith(expect.objectContaining({ dealId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { dealId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDeal, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDeal(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
