/**
 * EconomicRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EconomicRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EconomicRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EconomicRepository,
} from "@partnora/services/economics";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EconomicRepositoryDdb } from "./economic-repository.ddb.js";

/**
 * EconomicRepositoryAdapter
 *
 * Implements EconomicRepository port for infrastructure layer.
 */
export class EconomicRepositoryAdapter implements EconomicRepository {
  private readonly ddb: EconomicRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EconomicRepositoryDdb(this.dynamoClient);
  }

  async listEconomicsSnapshots(input: Parameters<EconomicRepository['listEconomicsSnapshots']>[0]): Promise<Awaited<ReturnType<EconomicRepository['listEconomicsSnapshots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEconomicsSnapshots(input);
  }

  async createEconomicsSnapshot(input: Parameters<EconomicRepository['createEconomicsSnapshot']>[0]): Promise<Awaited<ReturnType<EconomicRepository['createEconomicsSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createEconomicsSnapshot(input);
  }

  async getEconomicsSnapshot(input: Parameters<EconomicRepository['getEconomicsSnapshot']>[0]): Promise<Awaited<ReturnType<EconomicRepository['getEconomicsSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEconomicsSnapshot(input);
  }
}
