/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as auditsRoutes from "../../domains/audits/routes/index.js";
import * as channelsRoutes from "../../domains/channels/routes/index.js";
import * as conflictsRoutes from "../../domains/conflicts/routes/index.js";
import * as datapurposeRoutes from "../../domains/datapurpose/routes/index.js";
import * as dealsRoutes from "../../domains/deals/routes/index.js";
import * as economicsRoutes from "../../domains/economics/routes/index.js";
import * as gatesRoutes from "../../domains/gates/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as opportunitiesRoutes from "../../domains/opportunities/routes/index.js";
import * as ownershipRoutes from "../../domains/ownership/routes/index.js";
import * as partnersRoutes from "../../domains/partners/routes/index.js";
import * as pilotsRoutes from "../../domains/pilots/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "audits", mod: auditsRoutes },
  { domain: "channels", mod: channelsRoutes },
  { domain: "conflicts", mod: conflictsRoutes },
  { domain: "datapurpose", mod: datapurposeRoutes },
  { domain: "deals", mod: dealsRoutes },
  { domain: "economics", mod: economicsRoutes },
  { domain: "gates", mod: gatesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "opportunities", mod: opportunitiesRoutes },
  { domain: "ownership", mod: ownershipRoutes },
  { domain: "partners", mod: partnersRoutes },
  { domain: "pilots", mod: pilotsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
