/**
 * GetPilot handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPilot } from "@partnora/api-server/domains/pilots/handlers";
import type { PilotsDDDDependencies } from "@partnora/api-server/domains/pilots";
import { createPilot as createPilotEntity } from "@partnora/factories/pilots";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { PILOTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPilot", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PilotsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PilotsDDDDependencies>(
      PILOTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPilotEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPilot, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { pilotId: entity.id };

    await getPilot(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPilot.execute).toHaveBeenCalledWith(expect.objectContaining({ pilotId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { pilotId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPilot, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPilot(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
