/**
 * ExecuteListEconomicsSnapshots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEconomicsSnapshots Use Case
 *
 * DDD: Application use case for list Economic.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEconomicsSnapshotsInput, ListEconomicsSnapshotsOutput } from "../dto/economic.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { EconomicRepository } from "../ports";

export class ExecuteListEconomicsSnapshots {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly economic: EconomicRepository
  ) {}

  async execute(input: ListEconomicsSnapshotsInput): Promise<ListEconomicsSnapshotsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ecoId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.economic.listEconomicsSnapshots({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEconomicsSnapshotsOutput;
  }
}
