/**
 * ExecuteGetEconomicsSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEconomicsSnapshot Use Case
 *
 * DDD: Application use case for get Economic.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEconomicsSnapshotInput, GetEconomicsSnapshotOutput } from "../dto/economic.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { EconomicRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetEconomicsSnapshot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly economic: EconomicRepository
  ) {}

  async execute(input: GetEconomicsSnapshotInput): Promise<GetEconomicsSnapshotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ecoId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).economicsSnapshotId) {
      throw new ValidationError("economicsSnapshotId is required");
    }
    const economicssnapshotId = (input as any).economicsSnapshotId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.economic.getEconomicsSnapshot({ economicsSnapshotId: economicssnapshotId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${economicssnapshotId}`);
    }

    return entity as GetEconomicsSnapshotOutput;
  }
}
