/**
 * OwnershipRuleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OwnershipRuleRepository Port
 *
 * DDD: Application port for ownershiprulerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateOwnershipRuleInput, CreateOwnershipRuleOutput, GetOwnershipRuleInput, GetOwnershipRuleOutput, ListOwnershipRulesInput, ListOwnershipRulesOutput, UpdateOwnershipRuleInput, UpdateOwnershipRuleOutput } from "../dto/ownership-rule.dto";
export interface OwnershipRuleRepository {
  listOwnershipRules(input: ListOwnershipRulesInput): Promise<ListOwnershipRulesOutput>;
  createOwnershipRule(input: CreateOwnershipRuleInput): Promise<CreateOwnershipRuleOutput>;
  getOwnershipRule(input: GetOwnershipRuleInput): Promise<GetOwnershipRuleOutput>;
  updateOwnershipRule(input: UpdateOwnershipRuleInput): Promise<UpdateOwnershipRuleOutput>;
}

export type { CreateOwnershipRuleInput, CreateOwnershipRuleOutput, GetOwnershipRuleInput, GetOwnershipRuleOutput, ListOwnershipRulesInput, ListOwnershipRulesOutput, UpdateOwnershipRuleInput, UpdateOwnershipRuleOutput } from "../dto/ownership-rule.dto";
