/**
 * ExecuteListOpportunities - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOpportunities Use Case
 *
 * DDD: Application use case for list Opportunity.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOpportunitiesInput, ListOpportunitiesOutput } from "../dto/opportunity.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { OpportunityRepository } from "../ports";

export class ExecuteListOpportunities {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly opportunity: OpportunityRepository
  ) {}

  async execute(input: ListOpportunitiesInput): Promise<ListOpportunitiesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oppId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.opportunity.listOpportunities({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOpportunitiesOutput;
  }
}
