/**
 * ExecuteCreateOpportunity - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateOpportunity Use Case
 *
 * DDD: Application use case for create Opportunity.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateOpportunityInput, CreateOpportunityOutput } from "../dto/opportunity.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { OpportunityRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateOpportunity {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly opportunity: OpportunityRepository
  ) {}

  async execute(input: CreateOpportunityInput): Promise<CreateOpportunityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oppId();

    // All field names extracted from OpenAPI spec: partnerId, thesis, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.partnerId) {
      throw new ValidationError("partnerId is required");
    }
    if (!input.title) {
      throw new ValidationError("title is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (opportunities domain)
    const entityId = this.idGenerator.oppId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.opportunity.createOpportunity({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateOpportunityOutput;
  }
}
