/**
 * ExecuteAdvanceOpportunity - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAdvanceOpportunity Use Case
 *
 * DDD: Application use case for get Advance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AdvanceOpportunityInput, AdvanceOpportunityOutput } from "../dto/advance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { AdvanceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAdvanceOpportunity {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly advance: AdvanceRepository
  ) {}

  async execute(input: AdvanceOpportunityInput): Promise<AdvanceOpportunityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oppId();

    // All field names extracted from OpenAPI spec: status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).opportunityId) {
      throw new ValidationError("opportunityId is required");
    }
    const opportunityId = (input as any).opportunityId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.advance.advanceOpportunity({ opportunityId: opportunityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${opportunityId}`);
    }

    return entity as AdvanceOpportunityOutput;
  }
}
