/**
 * MetricRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MetricRepository Port
 *
 * DDD: Application port for metricrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestChannelMetricsInput, IngestChannelMetricsOutput } from "../dto/metric.dto";
export interface MetricRepository {
  ingestChannelMetrics(input: IngestChannelMetricsInput): Promise<IngestChannelMetricsOutput>;
}

export type { IngestChannelMetricsInput, IngestChannelMetricsOutput } from "../dto/metric.dto";
