/**
 * OpportunityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OpportunityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OpportunityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OpportunityRepository,
} from "@partnora/services/opportunities";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OpportunityRepositoryDdb } from "./opportunity-repository.ddb.js";

/**
 * OpportunityRepositoryAdapter
 *
 * Implements OpportunityRepository port for infrastructure layer.
 */
export class OpportunityRepositoryAdapter implements OpportunityRepository {
  private readonly ddb: OpportunityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OpportunityRepositoryDdb(this.dynamoClient);
  }

  async listOpportunities(input: Parameters<OpportunityRepository['listOpportunities']>[0]): Promise<Awaited<ReturnType<OpportunityRepository['listOpportunities']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listOpportunities(input);
  }

  async createOpportunity(input: Parameters<OpportunityRepository['createOpportunity']>[0]): Promise<Awaited<ReturnType<OpportunityRepository['createOpportunity']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createOpportunity(input);
  }

  async getOpportunity(input: Parameters<OpportunityRepository['getOpportunity']>[0]): Promise<Awaited<ReturnType<OpportunityRepository['getOpportunity']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOpportunity(input);
  }
}
