/**
 * DeleteDataPurpose DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RevokeDataPurposeParams } from "@partnora/core/datapurpose";

export function createDeleteDataPurposeRequest(overrides: Partial<RevokeDataPurposeParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
