/**
 * GetDataPurpose DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDataPurposeParams } from "@partnora/core/datapurpose";

export function createGetDataPurposeRequest(overrides: Partial<GetDataPurposeParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
