/**
 * Handlers for Advance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OpportunitiesDomainModule } from "../dependencies/opportunities-ddd.dependencies.js";
import type { AdvanceOpportunityInput } from "@partnora/services/opportunities";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/opportunities/{opportunityId}/advance
 * Operation: advanceOpportunity
 */
export async function advanceOpportunity(
  request: FastifyRequest<{ Params: { opportunityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OpportunitiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AdvanceOpportunityInput = {
    opportunityId: request.params.opportunityId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.advances.get.execute(input);
  return reply.code(200).send(result);
}


