/**
 * Ownership DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Ownership Domain Module - Composition root
 *
 * DDD: Composition root for ownership domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  OwnershipRuleRepositoryAdapter,
} from "@partnora/adapters/ownership";
import { getIdGeneratorService } from "@partnora/adapters";
import type { AdapterDynamoDBClient } from "@partnora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateOwnershipRule,
  ExecuteGetOwnershipRule,
  ExecuteListOwnershipRules,
  ExecuteUpdateOwnershipRule,
} from "@partnora/services/ownership/usecases";
// Ports (interfaces)
import type {
  OwnershipRuleRepository,
} from "@partnora/services/ownership/ports";

export interface OwnershipDomainModule {
  repos: {
    rules: OwnershipRuleRepository;
  };
  useCases: {
    rules: {
      create: ExecuteCreateOwnershipRule;
      get: ExecuteGetOwnershipRule;
      list: ExecuteListOwnershipRules;
      update: ExecuteUpdateOwnershipRule;
    };
  };
}

export function buildOwnershipDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OwnershipDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      rules?: OwnershipRuleRepository;
    } = {};

    obj.rules = new OwnershipRuleRepositoryAdapter(dynamoClient);
    return {
      rules: obj.rules!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    rules: {
      create: new ExecuteCreateOwnershipRule(executionContext, idGenerator, repos.rules),
      get: new ExecuteGetOwnershipRule(executionContext, idGenerator, repos.rules),
      list: new ExecuteListOwnershipRules(executionContext, idGenerator, repos.rules),
      update: new ExecuteUpdateOwnershipRule(executionContext, idGenerator, repos.rules),
    },
  };
  return { repos, useCases: useCases as OwnershipDomainModule["useCases"] };
}
