/**
 * GetDataPurpose handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDataPurpose } from "@partnora/api-server/domains/datapurpose/handlers";
import type { DatapurposeDDDDependencies } from "@partnora/api-server/domains/datapurpose";
import { createDataPurpose as createDataPurposeEntity } from "@partnora/factories/datapurpose";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { DATAPURPOSE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDataPurpose", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DatapurposeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DatapurposeDDDDependencies>(
      DATAPURPOSE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDataPurposeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDataPurpose, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { dataPurposeId: entity.id };

    await getDataPurpose(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDataPurpose.execute).toHaveBeenCalledWith(expect.objectContaining({ dataPurposeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { dataPurposeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDataPurpose, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDataPurpose(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
