/**
 * ListDataPurposes handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDataPurposes } from "@partnora/api-server/domains/datapurpose/handlers";
import type { DatapurposeDDDDependencies } from "@partnora/api-server/domains/datapurpose";
import { createDataPurpose as createDataPurposeEntity } from "@partnora/factories/datapurpose";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { DATAPURPOSE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDataPurposes", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DatapurposeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DatapurposeDDDDependencies>(
      DATAPURPOSE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDataPurposeEntity({ orgId }),
      createDataPurposeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDataPurposes, "execute").mockResolvedValue(useCaseResult);

    await listDataPurposes(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDataPurposes.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
