/**
 * GetOpportunity handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getOpportunity } from "@partnora/api-server/domains/opportunities/handlers";
import type { OpportunitiesDDDDependencies } from "@partnora/api-server/domains/opportunities";
import { createOpportunity as createOpportunityEntity } from "@partnora/factories/opportunities";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { OPPORTUNITIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetOpportunity", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OpportunitiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OpportunitiesDDDDependencies>(
      OPPORTUNITIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createOpportunityEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetOpportunity, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { opportunityId: entity.id };

    await getOpportunity(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetOpportunity.execute).toHaveBeenCalledWith(expect.objectContaining({ opportunityId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { opportunityId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetOpportunity, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getOpportunity(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
