/**
 * ListOpportunities handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listOpportunities } from "@partnora/api-server/domains/opportunities/handlers";
import type { OpportunitiesDDDDependencies } from "@partnora/api-server/domains/opportunities";
import { createOpportunity as createOpportunityEntity } from "@partnora/factories/opportunities";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { OPPORTUNITIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListOpportunities", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OpportunitiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OpportunitiesDDDDependencies>(
      OPPORTUNITIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createOpportunityEntity({ orgId }),
      createOpportunityEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListOpportunities, "execute").mockResolvedValue(useCaseResult);

    await listOpportunities(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListOpportunities.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
