/**
 * Export DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Export DTOs
 *
 * DDD: Application DTOs for Export use cases.
 */

import type { CreateAuditExportRequestInput, GetAuditExportParams, ListAuditExportsParams } from "@partnora/core/audits/types";

export type ListAuditExportsInput = ListAuditExportsParams;

export type CreateAuditExportInput = CreateAuditExportRequestInput;

export type GetAuditExportInput = GetAuditExportParams;

export type ListAuditExportsOutput = {};

export type CreateAuditExportOutput = {};

export type GetAuditExportOutput = {};
