/**
 * Handlers for Conflict
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConflictsDomainModule } from "../dependencies/conflicts-ddd.dependencies.js";
import type { CreateConflictInput, GetConflictInput, ListConflictsInput } from "@partnora/services/conflicts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/conflicts
 * Operation: listConflicts
 */
export async function listConflicts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dealId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ConflictsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListConflictsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.conflicts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/conflicts
 * Operation: createConflict
 */
export async function createConflict(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConflictsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateConflictInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.conflicts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/conflicts/{conflictId}
 * Operation: getConflict
 */
export async function getConflict(
  request: FastifyRequest<{ Params: { conflictId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConflictsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetConflictInput = {
    conflictId: request.params.conflictId,
  };
  const result = await deps.useCases.conflicts.get.execute(input);
  return reply.code(200).send(result);
}


