/**
 * Repository interface for Partner
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PartnerEntity
} from "../models/partner.entity.js";
import type {
  ListPartnersParams,
  Partner,
  UpdatePartnerRequestInput
} from "../types/index.js";
/**
 * PartnerRepository Interface
 */
export interface PartnerRepository extends CreateUpdateReadRepository<PartnerEntity, Partner, UpdatePartnerRequestInput, string, ListPartnersParams> {

}
