/**
 * Routes for OwnershipRule
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createOwnershipRule, getOwnershipRule, listOwnershipRules, updateOwnershipRule } from "../handlers/ownership-rule.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ownershipRuleRoutes(fastify: FastifyInstance) {
  // POST /v1/ownership-rules (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/ownership-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOwnershipDependenciesForRequest();
        await createOwnershipRule(request, reply, deps);
      });
    }
  );


  // GET /v1/ownership-rules (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ownership-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOwnershipDependenciesForRequest();
        await listOwnershipRules(request, reply, deps);
      });
    }
  );


  // GET /v1/ownership-rules/{ownershipRuleId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ownership-rules/:ownershipRuleId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ownershipRuleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOwnershipDependenciesForRequest();
        await getOwnershipRule(request, reply, deps);
      });
    }
  );


  // PATCH /v1/ownership-rules/{ownershipRuleId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/ownership-rules/:ownershipRuleId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ownershipRuleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOwnershipDependenciesForRequest();
        await updateOwnershipRule(request, reply, deps);
      });
    }
  );


}
