/**
 * Handlers for Economic
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EconomicsDomainModule } from "../dependencies/economics-ddd.dependencies.js";
import type { CreateEconomicsSnapshotInput, GetEconomicsSnapshotInput, ListEconomicsSnapshotsInput } from "@partnora/services/economics";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/economics
 * Operation: listEconomicsSnapshots
 */
export async function listEconomicsSnapshots(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dealId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EconomicsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEconomicsSnapshotsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.economics.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/economics
 * Operation: createEconomicsSnapshot
 */
export async function createEconomicsSnapshot(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EconomicsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateEconomicsSnapshotInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.economics.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/economics/{economicsSnapshotId}
 * Operation: getEconomicsSnapshot
 */
export async function getEconomicsSnapshot(
  request: FastifyRequest<{ Params: { economicsSnapshotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EconomicsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEconomicsSnapshotInput = {
    economicsSnapshotId: request.params.economicsSnapshotId,
  };
  const result = await deps.useCases.economics.get.execute(input);
  return reply.code(200).send(result);
}


