/**
 * Deal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DealEntity } from "@partnora/core/deals/models/index.js";
import { dealsSchemas } from "@partnora/core/deals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "deal";

export function createDeal(overrides: Partial<DealEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    commercialModel: overrides.commercialModel ?? "revenueShare",
    dealId: overrides.dealId ?? `deal_${ulid().toLowerCase()}`,
    gatesComplete: overrides.gatesComplete ?? faker.datatype.boolean(),
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return dealsSchemas.Deal.parse(raw);
}

export function dealBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDeal(overrides));
}
