/**
 * GetEconomic DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetEconomicsSnapshotParams } from "@partnora/core/economics";

export function createGetEconomicRequest(overrides: Partial<GetEconomicsSnapshotParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
