/**
 * DataPurpose Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DataPurposeEntity } from "@partnora/core/datapurpose/models/index.js";
import { datapurposeSchemas } from "@partnora/core/datapurpose";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dpr";

export function createDataPurpose(overrides: Partial<DataPurposeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dataPurposeId: overrides.dataPurposeId ?? `dpr_${ulid().toLowerCase()}`,
    dealId: overrides.dealId ?? faker.string.uuid(),
    purpose: overrides.purpose ?? faker.lorem.word(),
    retentionDays: overrides.retentionDays ?? faker.number.int(),
    ...overrides,
  };

  return datapurposeSchemas.DataPurpose.parse(raw);
}

export function dataPurposeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDataPurpose(overrides));
}
