/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Partners Domain Use Cases
 * 
 * List of all use case names for the partners domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PARTNERS_USE_CASES = [
  "executeCreatePartner",
  "executeGetPartner",
  "executeListPartners",
  "executeUpdatePartner"
] as const;
