/**
 * Handlers for Launch
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DealsDomainModule } from "../dependencies/deals-ddd.dependencies.js";
import type { LaunchDealInput } from "@partnora/services/deals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/deals/{dealId}/launch
 * Operation: launchDeal
 */
export async function launchDeal(
  request: FastifyRequest<{ Params: { dealId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: LaunchDealInput = {
    dealId: request.params.dealId,
  };
  const result = await deps.useCases.launches.get.execute(input);
  return reply.code(200).send(result);
}


