/**
 * Handlers for MaReassessment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DealsDomainModule } from "../dependencies/deals-ddd.dependencies.js";
import type { StartMaReassessmentInput } from "@partnora/services/deals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/deals/ma-reassessments
 * Operation: startMaReassessment
 */
export async function startMaReassessment(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: StartMaReassessmentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.maReassessments.create.execute(input);
  return reply.code(200).send(result);
}


