/**
 * OwnershipRuleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OwnershipRuleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OwnershipRuleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OwnershipRuleRepository,
} from "@partnora/services/ownership";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OwnershipRuleRepositoryDdb } from "./ownership-rule-repository.ddb.js";

/**
 * OwnershipRuleRepositoryAdapter
 *
 * Implements OwnershipRuleRepository port for infrastructure layer.
 */
export class OwnershipRuleRepositoryAdapter implements OwnershipRuleRepository {
  private readonly ddb: OwnershipRuleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OwnershipRuleRepositoryDdb(this.dynamoClient);
  }

  async listOwnershipRules(input: Parameters<OwnershipRuleRepository['listOwnershipRules']>[0]): Promise<Awaited<ReturnType<OwnershipRuleRepository['listOwnershipRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listOwnershipRules(input);
  }

  async createOwnershipRule(input: Parameters<OwnershipRuleRepository['createOwnershipRule']>[0]): Promise<Awaited<ReturnType<OwnershipRuleRepository['createOwnershipRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createOwnershipRule(input);
  }

  async getOwnershipRule(input: Parameters<OwnershipRuleRepository['getOwnershipRule']>[0]): Promise<Awaited<ReturnType<OwnershipRuleRepository['getOwnershipRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOwnershipRule(input);
  }

  async updateOwnershipRule(input: Parameters<OwnershipRuleRepository['updateOwnershipRule']>[0]): Promise<Awaited<ReturnType<OwnershipRuleRepository['updateOwnershipRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateOwnershipRule(input);
  }
}
