/**
 * ChannelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChannelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ChannelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ChannelRepository,
} from "@partnora/services/channels";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ChannelRepositoryDdb } from "./channel-repository.ddb.js";

/**
 * ChannelRepositoryAdapter
 *
 * Implements ChannelRepository port for infrastructure layer.
 */
export class ChannelRepositoryAdapter implements ChannelRepository {
  private readonly ddb: ChannelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ChannelRepositoryDdb(this.dynamoClient);
  }

  async listChannelNodes(input: Parameters<ChannelRepository['listChannelNodes']>[0]): Promise<Awaited<ReturnType<ChannelRepository['listChannelNodes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listChannelNodes(input);
  }

  async createChannelNode(input: Parameters<ChannelRepository['createChannelNode']>[0]): Promise<Awaited<ReturnType<ChannelRepository['createChannelNode']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createChannelNode(input);
  }

  async getChannelNode(input: Parameters<ChannelRepository['getChannelNode']>[0]): Promise<Awaited<ReturnType<ChannelRepository['getChannelNode']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getChannelNode(input);
  }
}
