/**
 * MetricRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MetricRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MetricRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MetricRepository,
} from "@partnora/services/channels";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MetricRepositoryDdb } from "./metric-repository.ddb.js";

/**
 * MetricRepositoryAdapter
 *
 * Implements MetricRepository port for infrastructure layer.
 */
export class MetricRepositoryAdapter implements MetricRepository {
  private readonly ddb: MetricRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MetricRepositoryDdb(this.dynamoClient);
  }

  async ingestChannelMetrics(input: Parameters<MetricRepository['ingestChannelMetrics']>[0]): Promise<Awaited<ReturnType<MetricRepository['ingestChannelMetrics']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestChannelMetrics(input);
  }
}
