/**
 * Deal Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/deals.openapi.types.js";
import { schemas } from "../schemas/deals.schemas.js";

/**
 * Entity: DealEntity
 * Description: Represents the Deal domain model.
 * Source: schemas.Deal
 * Type: Domain Entity (API)
 */
export const DealEntitySchema = schemas.Deal;
export type DealEntity = components["schemas"]["Deal"];
