/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { attachParentRoutes } from "./attach-parent.routes.js";
export { pilotRoutes } from "./pilot.routes.js";
export { quarantineRoutes } from "./quarantine.routes.js";
