/**
 * Routes for Pilot
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPilot, getPilot, listPilots } from "../handlers/pilot.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function pilotRoutes(fastify: FastifyInstance) {
  // POST /v1/pilots (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/pilots",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await createPilot(request, reply, deps);
      });
    }
  );


  // GET /v1/pilots (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pilots",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await listPilots(request, reply, deps);
      });
    }
  );


  // GET /v1/pilots/{pilotId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pilots/:pilotId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await getPilot(request, reply, deps);
      });
    }
  );


}
