/**
 * Economics DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Economics Domain Module - Composition root
 *
 * DDD: Composition root for economics domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EconomicRepositoryAdapter,
} from "@partnora/adapters/economics";
import { getIdGeneratorService } from "@partnora/adapters";
import type { AdapterDynamoDBClient } from "@partnora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateEconomicsSnapshot,
  ExecuteGetEconomicsSnapshot,
  ExecuteListEconomicsSnapshots,
} from "@partnora/services/economics/usecases";
// Ports (interfaces)
import type {
  EconomicRepository,
} from "@partnora/services/economics/ports";

export interface EconomicsDomainModule {
  repos: {
    economics: EconomicRepository;
  };
  useCases: {
    economics: {
      create: ExecuteCreateEconomicsSnapshot;
      get: ExecuteGetEconomicsSnapshot;
      list: ExecuteListEconomicsSnapshots;
    };
  };
}

export function buildEconomicsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EconomicsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      economics?: EconomicRepository;
    } = {};

    obj.economics = new EconomicRepositoryAdapter(dynamoClient);
    return {
      economics: obj.economics!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    economics: {
      create: new ExecuteCreateEconomicsSnapshot(executionContext, idGenerator, repos.economics),
      get: new ExecuteGetEconomicsSnapshot(executionContext, idGenerator, repos.economics),
      list: new ExecuteListEconomicsSnapshots(executionContext, idGenerator, repos.economics),
    },
  };
  return { repos, useCases: useCases as EconomicsDomainModule["useCases"] };
}
