/**
 * ListChannel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListChannelNodesParams } from "@partnora/core/channels";

export function createListChannelRequest(overrides: Partial<ListChannelNodesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
