/**
 * Deal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deal DTOs
 *
 * DDD: Application DTOs for Deal use cases.
 */

import type { CreateDealRequestInput, GetDealParams, ListDealsParams, UpdateDealParams, UpdateDealRequestInput } from "@partnora/core/deals/types";

export type ListDealsInput = ListDealsParams;

export type CreateDealInput = CreateDealRequestInput;

export type GetDealInput = GetDealParams;

export type UpdateDealInput = UpdateDealParams & UpdateDealRequestInput;

export type ListDealsOutput = {};

export type CreateDealOutput = {};

export type GetDealOutput = {};

export type UpdateDealOutput = {};
