/**
 * Exit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exit DTOs
 *
 * DDD: Application DTOs for Exit use cases.
 */

import type { StartDealExitParams } from "@partnora/core/deals/types";

export type StartDealExitInput = StartDealExitParams;

export type StartDealExitOutput = {};
