/**
 * MaReassessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MaReassessment DTOs
 *
 * DDD: Application DTOs for MaReassessment use cases.
 */

import type { StartMaReassessmentRequestInput } from "@partnora/core/deals/types";

export type StartMaReassessmentInput = StartMaReassessmentRequestInput;

export type StartMaReassessmentOutput = {};
