/**
 * SubmitGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitGate DTOs
 *
 * DDD: Application DTOs for SubmitGate use cases.
 */

import type { SubmitDealToGatesParams } from "@partnora/core/deals/types";

export type SubmitDealToGatesInput = SubmitDealToGatesParams;

export type SubmitDealToGatesOutput = {};
