/**
 * Handlers for AttachParent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PilotsDomainModule } from "../dependencies/pilots-ddd.dependencies.js";
import type { AttachPilotParentInput } from "@partnora/services/pilots";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/pilots/{pilotId}/attach-parent
 * Operation: attachPilotParent
 */
export async function attachPilotParent(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AttachPilotParentInput = {
    pilotId: request.params.pilotId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attachParents.get.execute(input);
  return reply.code(200).send(result);
}


