/**
 * Handlers for Pilot
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PilotsDomainModule } from "../dependencies/pilots-ddd.dependencies.js";
import type { CreatePilotInput, GetPilotInput, ListPilotsInput } from "@partnora/services/pilots";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pilots
 * Operation: listPilots
 */
export async function listPilots(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], parentDealId?: string | string[], orphansOnly?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPilotsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.pilots.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/pilots
 * Operation: createPilot
 */
export async function createPilot(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePilotInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.pilots.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/pilots/{pilotId}
 * Operation: getPilot
 */
export async function getPilot(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPilotInput = {
    pilotId: request.params.pilotId,
  };
  const result = await deps.useCases.pilots.get.execute(input);
  return reply.code(200).send(result);
}


