/**
 * AcceptRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRepository Port
 *
 * DDD: Application port for acceptrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcceptConflictMitigationInput, AcceptConflictMitigationOutput } from "../dto/accept.dto";
export interface AcceptRepository {
  acceptConflictMitigation(input: AcceptConflictMitigationInput): Promise<AcceptConflictMitigationOutput>;
}

export type { AcceptConflictMitigationInput, AcceptConflictMitigationOutput } from "../dto/accept.dto";
