/**
 * DataPurposeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataPurposeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataPurposeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataPurposeRepository,
} from "@partnora/services/datapurpose";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataPurposeRepositoryDdb } from "./data-purpose-repository.ddb.js";

/**
 * DataPurposeRepositoryAdapter
 *
 * Implements DataPurposeRepository port for infrastructure layer.
 */
export class DataPurposeRepositoryAdapter implements DataPurposeRepository {
  private readonly ddb: DataPurposeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataPurposeRepositoryDdb(this.dynamoClient);
  }

  async listDataPurposes(input: Parameters<DataPurposeRepository['listDataPurposes']>[0]): Promise<Awaited<ReturnType<DataPurposeRepository['listDataPurposes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataPurposes(input);
  }

  async createDataPurpose(input: Parameters<DataPurposeRepository['createDataPurpose']>[0]): Promise<Awaited<ReturnType<DataPurposeRepository['createDataPurpose']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDataPurpose(input);
  }

  async getDataPurpose(input: Parameters<DataPurposeRepository['getDataPurpose']>[0]): Promise<Awaited<ReturnType<DataPurposeRepository['getDataPurpose']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataPurpose(input);
  }

  async revokeDataPurpose(input: Parameters<DataPurposeRepository['revokeDataPurpose']>[0]): Promise<Awaited<ReturnType<DataPurposeRepository['revokeDataPurpose']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.revokeDataPurpose(input);
  }
}
