/**
 * AttachParentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttachParentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttachParentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AttachParentRepository,
} from "@partnora/services/pilots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AttachParentRepositoryDdb } from "./attach-parent-repository.ddb.js";

/**
 * AttachParentRepositoryAdapter
 *
 * Implements AttachParentRepository port for infrastructure layer.
 */
export class AttachParentRepositoryAdapter implements AttachParentRepository {
  private readonly ddb: AttachParentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AttachParentRepositoryDdb(this.dynamoClient);
  }

  async attachPilotParent(input: Parameters<AttachParentRepository['attachPilotParent']>[0]): Promise<Awaited<ReturnType<AttachParentRepository['attachPilotParent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attachPilotParent(input);
  }
}
