/**
 * PilotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PilotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PilotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PilotRepository,
} from "@partnora/services/pilots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PilotRepositoryDdb } from "./pilot-repository.ddb.js";

/**
 * PilotRepositoryAdapter
 *
 * Implements PilotRepository port for infrastructure layer.
 */
export class PilotRepositoryAdapter implements PilotRepository {
  private readonly ddb: PilotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PilotRepositoryDdb(this.dynamoClient);
  }

  async listPilots(input: Parameters<PilotRepository['listPilots']>[0]): Promise<Awaited<ReturnType<PilotRepository['listPilots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPilots(input);
  }

  async createPilot(input: Parameters<PilotRepository['createPilot']>[0]): Promise<Awaited<ReturnType<PilotRepository['createPilot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPilot(input);
  }

  async getPilot(input: Parameters<PilotRepository['getPilot']>[0]): Promise<Awaited<ReturnType<PilotRepository['getPilot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPilot(input);
  }
}
