/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-ownership-rule.handler.test.js";
export * from "./get-ownership-rule.handler.test.js";
export * from "./list-ownership-rules.handler.test.js";
export * from "./update-ownership-rule.handler.test.js";
