/**
 * UpdateOwnershipRule handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateOwnershipRule } from "@partnora/api-server/domains/ownership/handlers";
import type { OwnershipDDDDependencies } from "@partnora/api-server/domains/ownership";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { OWNERSHIP_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateOwnershipRule", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OwnershipDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OwnershipDDDDependencies>(
      OWNERSHIP_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { ownershipRuleId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateOwnershipRule, "execute").mockResolvedValue(useCaseResult);

    await updateOwnershipRule(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateOwnershipRule.execute).toHaveBeenCalledWith(expect.objectContaining({ ownershipRuleId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
