/**
 * Economic DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: economics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Economic DTOs
 *
 * DDD: Application DTOs for Economic use cases.
 */

import type { CreateEconomicsSnapshotRequestInput, GetEconomicsSnapshotParams, ListEconomicsSnapshotsParams } from "@partnora/core/economics/types";

export type ListEconomicsSnapshotsInput = ListEconomicsSnapshotsParams;

export type CreateEconomicsSnapshotInput = CreateEconomicsSnapshotRequestInput;

export type GetEconomicsSnapshotInput = GetEconomicsSnapshotParams;

export type ListEconomicsSnapshotsOutput = {};

export type CreateEconomicsSnapshotOutput = {};

export type GetEconomicsSnapshotOutput = {};
