/**
 * DealRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DealRepository Port
 *
 * DDD: Application port for dealrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDealInput, CreateDealOutput, GetDealInput, GetDealOutput, ListDealsInput, ListDealsOutput, UpdateDealInput, UpdateDealOutput } from "../dto/deal.dto";
export interface DealRepository {
  listDeals(input: ListDealsInput): Promise<ListDealsOutput>;
  createDeal(input: CreateDealInput): Promise<CreateDealOutput>;
  getDeal(input: GetDealInput): Promise<GetDealOutput>;
  updateDeal(input: UpdateDealInput): Promise<UpdateDealOutput>;
}

export type { CreateDealInput, CreateDealOutput, GetDealInput, GetDealOutput, ListDealsInput, ListDealsOutput, UpdateDealInput, UpdateDealOutput } from "../dto/deal.dto";
