/**
 * ExitRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExitRepository Port
 *
 * DDD: Application port for exitrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { StartDealExitInput, StartDealExitOutput } from "../dto/exit.dto";
export interface ExitRepository {
  startDealExit(input: StartDealExitInput): Promise<StartDealExitOutput>;
}

export type { StartDealExitInput, StartDealExitOutput } from "../dto/exit.dto";
