/**
 * MaReassessmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MaReassessmentRepository Port
 *
 * DDD: Application port for mareassessmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { StartMaReassessmentInput, StartMaReassessmentOutput } from "../dto/ma-reassessment.dto";
export interface MaReassessmentRepository {
  startMaReassessment(input: StartMaReassessmentInput): Promise<StartMaReassessmentOutput>;
}

export type { StartMaReassessmentInput, StartMaReassessmentOutput } from "../dto/ma-reassessment.dto";
