/**
 * SubmitGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitGateRepository Port
 *
 * DDD: Application port for submitgaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitDealToGatesInput, SubmitDealToGatesOutput } from "../dto/submit-gate.dto";
export interface SubmitGateRepository {
  submitDealToGates(input: SubmitDealToGatesInput): Promise<SubmitDealToGatesOutput>;
}

export type { SubmitDealToGatesInput, SubmitDealToGatesOutput } from "../dto/submit-gate.dto";
