/**
 * Handlers for DataPurpose
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DatapurposeDomainModule } from "../dependencies/datapurpose-ddd.dependencies.js";
import type { CreateDataPurposeInput, GetDataPurposeInput, ListDataPurposesInput, RevokeDataPurposeInput } from "@partnora/services/datapurpose";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/data-purposes
 * Operation: listDataPurposes
 */
export async function listDataPurposes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dealId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DatapurposeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDataPurposesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.dataPurposes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/data-purposes
 * Operation: createDataPurpose
 */
export async function createDataPurpose(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DatapurposeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDataPurposeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dataPurposes.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/data-purposes/{dataPurposeId}
 * Operation: getDataPurpose
 */
export async function getDataPurpose(
  request: FastifyRequest<{ Params: { dataPurposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DatapurposeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDataPurposeInput = {
    dataPurposeId: request.params.dataPurposeId,
  };
  const result = await deps.useCases.dataPurposes.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v1/data-purposes/{dataPurposeId}
 * Operation: revokeDataPurpose
 */
export async function revokeDataPurpose(
  request: FastifyRequest<{ Params: { dataPurposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DatapurposeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RevokeDataPurposeInput = {
    dataPurposeId: request.params.dataPurposeId,
  };
  const result = await deps.useCases.dataPurposes.get.execute(input);
  return reply.code(204).send(result);
}


