/**
 * Handlers for ExportCheck
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DatapurposeDomainModule } from "../dependencies/datapurpose-ddd.dependencies.js";
import type { CheckDataExportInput } from "@partnora/services/datapurpose";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/data-purposes/export-check
 * Operation: checkDataExport
 */
export async function checkDataExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DatapurposeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CheckDataExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exportChecks.get.execute(input);
  return reply.code(200).send(result);
}


