/**
 * Routes for Partner
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPartner, getPartner, listPartners, updatePartner } from "../handlers/partner.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function partnerRoutes(fastify: FastifyInstance) {
  // POST /v1/partners (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/partners",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPartnersDependenciesForRequest();
        await createPartner(request, reply, deps);
      });
    }
  );


  // GET /v1/partners (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/partners",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPartnersDependenciesForRequest();
        await listPartners(request, reply, deps);
      });
    }
  );


  // GET /v1/partners/{partnerId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/partners/:partnerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPartnersDependenciesForRequest();
        await getPartner(request, reply, deps);
      });
    }
  );


  // PATCH /v1/partners/{partnerId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/partners/:partnerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPartnersDependenciesForRequest();
        await updatePartner(request, reply, deps);
      });
    }
  );


}
