/**
 * Handlers for OwnershipRule
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ownership
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OwnershipDomainModule } from "../dependencies/ownership-ddd.dependencies.js";
import type { CreateOwnershipRuleInput, GetOwnershipRuleInput, ListOwnershipRulesInput, UpdateOwnershipRuleInput } from "@partnora/services/ownership";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/ownership-rules
 * Operation: listOwnershipRules
 */
export async function listOwnershipRules(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dealId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: OwnershipDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListOwnershipRulesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.rules.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/ownership-rules
 * Operation: createOwnershipRule
 */
export async function createOwnershipRule(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: OwnershipDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateOwnershipRuleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rules.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/ownership-rules/{ownershipRuleId}
 * Operation: getOwnershipRule
 */
export async function getOwnershipRule(
  request: FastifyRequest<{ Params: { ownershipRuleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OwnershipDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOwnershipRuleInput = {
    ownershipRuleId: request.params.ownershipRuleId,
  };
  const result = await deps.useCases.rules.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/ownership-rules/{ownershipRuleId}
 * Operation: updateOwnershipRule
 */
export async function updateOwnershipRule(
  request: FastifyRequest<{ Params: { ownershipRuleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OwnershipDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateOwnershipRuleInput = {
    ownershipRuleId: request.params.ownershipRuleId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rules.update.execute(input);
  return reply.code(200).send(result);
}


