/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Opportunities Domain Use Cases
 * 
 * List of all use case names for the opportunities domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const OPPORTUNITIES_USE_CASES = [
  "executeAdvanceOpportunity",
  "executeCreateOpportunity",
  "executeGetOpportunity",
  "executeListOpportunities",
  "executeScoreOpportunity"
] as const;
