/**
 * GateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateRepository Port
 *
 * DDD: Application port for gaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideGateInput, DecideGateOutput, ListDealGatesInput, ListDealGatesOutput, SubmitGateEvidenceInput, SubmitGateEvidenceOutput } from "../dto/gate.dto";
export interface GateRepository {
  listDealGates(input: ListDealGatesInput): Promise<ListDealGatesOutput>;
  submitGateEvidence(input: SubmitGateEvidenceInput): Promise<SubmitGateEvidenceOutput>;
  decideGate(input: DecideGateInput): Promise<DecideGateOutput>;
}

export type { DecideGateInput, DecideGateOutput, ListDealGatesInput, ListDealGatesOutput, SubmitGateEvidenceInput, SubmitGateEvidenceOutput } from "../dto/gate.dto";
