/**
 * AttachParentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttachParentRepository Port
 *
 * DDD: Application port for attachparentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttachPilotParentInput, AttachPilotParentOutput } from "../dto/attach-parent.dto";
export interface AttachParentRepository {
  attachPilotParent(input: AttachPilotParentInput): Promise<AttachPilotParentOutput>;
}

export type { AttachPilotParentInput, AttachPilotParentOutput } from "../dto/attach-parent.dto";
