/**
 * Routes for DataPurpose
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: datapurpose
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDataPurpose, getDataPurpose, listDataPurposes, revokeDataPurpose } from "../handlers/data-purpose.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataPurposeRoutes(fastify: FastifyInstance) {
  // POST /v1/data-purposes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/data-purposes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDatapurposeDependenciesForRequest();
        await createDataPurpose(request, reply, deps);
      });
    }
  );


  // GET /v1/data-purposes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-purposes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDatapurposeDependenciesForRequest();
        await listDataPurposes(request, reply, deps);
      });
    }
  );


  // GET /v1/data-purposes/{dataPurposeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-purposes/:dataPurposeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dataPurposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDatapurposeDependenciesForRequest();
        await getDataPurpose(request, reply, deps);
      });
    }
  );


  // DELETE /v1/data-purposes/{dataPurposeId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/data-purposes/:dataPurposeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dataPurposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDatapurposeDependenciesForRequest();
        await revokeDataPurpose(request, reply, deps);
      });
    }
  );


}
