/**
 * QuarantinePilot handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { quarantinePilot } from "@partnora/api-server/domains/pilots/handlers";
import type { PilotsDDDDependencies } from "@partnora/api-server/domains/pilots";
import { createCreateQuarantineRequest } from "@partnora/factories/pilots";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { PILOTS_USE_CASES } from "../__factories__/use-cases.js";

describe("QuarantinePilot", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PilotsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PilotsDDDDependencies>(
      PILOTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateQuarantineRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeQuarantinePilot, "execute").mockResolvedValue(useCaseResult);

    await quarantinePilot(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeQuarantinePilot.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
