/**
 * PartnerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PartnerRepository Port
 *
 * DDD: Application port for partnerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePartnerInput, CreatePartnerOutput, GetPartnerInput, GetPartnerOutput, ListPartnersInput, ListPartnersOutput, UpdatePartnerInput, UpdatePartnerOutput } from "../dto/partner.dto";
export interface PartnerRepository {
  listPartners(input: ListPartnersInput): Promise<ListPartnersOutput>;
  createPartner(input: CreatePartnerInput): Promise<CreatePartnerOutput>;
  getPartner(input: GetPartnerInput): Promise<GetPartnerOutput>;
  updatePartner(input: UpdatePartnerInput): Promise<UpdatePartnerOutput>;
}

export type { CreatePartnerInput, CreatePartnerOutput, GetPartnerInput, GetPartnerOutput, ListPartnersInput, ListPartnersOutput, UpdatePartnerInput, UpdatePartnerOutput } from "../dto/partner.dto";
