/**
 * Repository interface for Opportunity
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OpportunityEntity
} from "../models/opportunity.entity.js";
import type {
  ListOpportunitiesParams,
  Opportunity
} from "../types/index.js";
/**
 * OpportunityRepository Interface
 */
export interface OpportunityRepository extends CreateReadRepository<OpportunityEntity, Opportunity, string, ListOpportunitiesParams> {

}
