/**
 * Routes for Channel
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createChannelNode, getChannelNode, listChannelNodes } from "../handlers/channel.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function channelRoutes(fastify: FastifyInstance) {
  // POST /v1/channels (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/channels",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getChannelsDependenciesForRequest();
        await createChannelNode(request, reply, deps);
      });
    }
  );


  // GET /v1/channels (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/channels",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getChannelsDependenciesForRequest();
        await listChannelNodes(request, reply, deps);
      });
    }
  );


  // GET /v1/channels/{channelNodeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/channels/:channelNodeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { channelNodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getChannelsDependenciesForRequest();
        await getChannelNode(request, reply, deps);
      });
    }
  );


}
