/**
 * Accept DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Accept DTOs
 *
 * DDD: Application DTOs for Accept use cases.
 */

import type { AcceptConflictMitigationParams, AcceptConflictMitigationRequestInput } from "@partnora/core/conflicts/types";

export type AcceptConflictMitigationInput = AcceptConflictMitigationParams & AcceptConflictMitigationRequestInput;

export type AcceptConflictMitigationOutput = {};
