/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { maReassessmentRoutes } from "./ma-reassessment.routes.js";
export { dealRoutes } from "./deal.routes.js";
export { exitRoutes } from "./exit.routes.js";
export { launchRoutes } from "./launch.routes.js";
export { remediateRoutes } from "./remediate.routes.js";
export { submitGateRoutes } from "./submit-gate.routes.js";
