/**
 * Pilot Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/pilots.openapi.types.js";
import { schemas } from "../schemas/pilots.schemas.js";

/**
 * Entity: PilotEntity
 * Description: Represents the Pilot domain model.
 * Source: schemas.Pilot
 * Type: Domain Entity (API)
 */
export const PilotEntitySchema = schemas.Pilot;
export type PilotEntity = components["schemas"]["Pilot"];
