/**
 * GetPartner handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: partners
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPartner } from "@partnora/api-server/domains/partners/handlers";
import type { PartnersDDDDependencies } from "@partnora/api-server/domains/partners";
import { createPartner as createPartnerEntity } from "@partnora/factories/partners";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@partnora/tests/shared";
import { PARTNERS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPartner", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PartnersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PartnersDDDDependencies>(
      PARTNERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPartnerEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPartner, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { partnerId: entity.id };

    await getPartner(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPartner.execute).toHaveBeenCalledWith(expect.objectContaining({ partnerId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { partnerId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPartner, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPartner(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
