/**
 * Conflict Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/conflicts.openapi.types.js";
import { schemas } from "../schemas/conflicts.schemas.js";

/**
 * Entity: ConflictEntity
 * Description: Represents the Conflict domain model.
 * Source: schemas.Conflict
 * Type: Domain Entity (API)
 */
export const ConflictEntitySchema = schemas.Conflict;
export type ConflictEntity = components["schemas"]["Conflict"];
