/**
 * OpportunityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: opportunities
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OpportunityRepository Port
 *
 * DDD: Application port for opportunityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateOpportunityInput, CreateOpportunityOutput, GetOpportunityInput, GetOpportunityOutput, ListOpportunitiesInput, ListOpportunitiesOutput } from "../dto/opportunity.dto";
export interface OpportunityRepository {
  listOpportunities(input: ListOpportunitiesInput): Promise<ListOpportunitiesOutput>;
  createOpportunity(input: CreateOpportunityInput): Promise<CreateOpportunityOutput>;
  getOpportunity(input: GetOpportunityInput): Promise<GetOpportunityOutput>;
}

export type { CreateOpportunityInput, CreateOpportunityOutput, GetOpportunityInput, GetOpportunityOutput, ListOpportunitiesInput, ListOpportunitiesOutput } from "../dto/opportunity.dto";
