/**
 * ExecuteCreateDeal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDeal Use Case
 *
 * DDD: Application use case for create Deal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDealInput, CreateDealOutput } from "../dto/deal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { DealRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDeal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deal: DealRepository
  ) {}

  async execute(input: CreateDealInput): Promise<CreateDealOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealId();

    // All field names extracted from OpenAPI spec: commercialModel, commercialTerms, exitTerms, inclusionKpis, opportunityId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.commercialModel) {
      throw new ValidationError("commercialModel is required");
    }
    if (!input.exitTerms) {
      throw new ValidationError("exitTerms is required");
    }
    if (!input.opportunityId) {
      throw new ValidationError("opportunityId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (deals domain)
    const entityId = this.idGenerator.dealId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.deal.createDeal({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDealOutput;
  }
}
