/**
 * ExecuteUpdateDeal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateDeal Use Case
 *
 * DDD: Application use case for update Deal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateDealInput, UpdateDealOutput } from "../dto/deal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { DealRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateDeal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deal: DealRepository
  ) {}

  async execute(input: UpdateDealInput): Promise<UpdateDealOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dealId) {
      throw new ValidationError("dealId is required");
    }
    const dealId = (input as any).dealId;

    // Load existing entity
    const existing = await this.deal.getDeal({ dealId: dealId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${dealId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.deal.updateDeal({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateDealOutput;
  }
}
