/**
 * ExecuteListConflicts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conflicts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListConflicts Use Case
 *
 * DDD: Application use case for list Conflict.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListConflictsInput, ListConflictsOutput } from "../dto/conflict.dto";
import type { ExecutionContextService, IdGeneratorService } from "@partnora/services/_shared/index.js";
import type { ConflictRepository } from "../ports";

export class ExecuteListConflicts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly conflict: ConflictRepository
  ) {}

  async execute(input: ListConflictsInput): Promise<ListConflictsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.conflict.listConflicts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListConflictsOutput;
  }
}
